# -*- coding: utf-8 -*-
"""data_sintetica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJOVYvd1jPu6Xc3hCAKr3tRpk_w1EgT9

Generador de dataset de queries médicas en español usando Claude API.
Diseñado para Google Colab. Cada bloque marcado con `# %%` es una celda.

Genera 500 queries (50 por cada una de las 10 áreas médicas) con la
distribución de tipos pedida y los devuelve como JSON estructurado.
"""

# %% [1] Instalación de dependencias
!pip install anthropic --quiet

# Celda 1.5: montar Drive y definir rutas persistentes
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from pathlib import Path
BASE = Path('/content/drive/MyDrive/fundamentos_eval_rag')
BASE.mkdir(parents=True, exist_ok=True)

# %% [2] Imports y configuración del cliente
import anthropic
import json
import time
import re
from pathlib import Path
from collections import Counter

# En Colab usa Secrets (panel izquierdo > 🔑) con el nombre ANTHROPIC_API_KEY
try:
    from google.colab import userdata
    API_KEY = userdata.get("ANTHROPIC_API_KEY")
except ImportError:
    import os
    API_KEY = os.environ.get("ANTHROPIC_API_KEY")

client = anthropic.Anthropic(api_key=API_KEY)

# Modelo: ajusta si quieres más calidad (opus) o más velocidad/costo (haiku)
MODELO = "claude-sonnet-4-6"

AREAS = [
    "Medicina general / familiar",
    "Medicina interna",
    "Pediatría",
    "Ginecología y obstetricia",
    "Cardiología",
    "Ortopedia y traumatología",
    "Dermatología",
    "Oftalmología",
    "Otorrinolaringología (ORL)",
    "Psiquiatría y salud mental",
]

# 20 + 10 + 8 + 7 + 5 = 50 por área
DISTRIBUCION = {
    "sintomas_primera_persona": {
        "n": 20,
        "descripcion": (
            "Descripciones de síntomas en primera persona, como si el paciente le "
            "contara a un amigo o tecleara en un buscador. Debe sentirse humano, "
            "con detalles de tiempo, contexto y emoción. "
            "Ejemplo: 'desde hace 3 días me duele la cabeza por las tardes y "
            "siento como mareo cuando me levanto rápido'."
        ),
    },
    "medicamentos": {
        "n": 10,
        "descripcion": (
            "Preguntas sobre medicamentos: efectos secundarios, interacciones, "
            "dosis, dudas de uso. Formato típico: 'tomé X y siento Y', "
            "'¿puedo combinar X con Y?', '¿qué pasa si me salté la dosis?'."
        ),
    },
    "interpretacion_resultados": {
        "n": 8,
        "descripcion": (
            "Interpretación de resultados de laboratorio, imagen o estudios. "
            "Ejemplo: 'me salió el colesterol LDL en 180, ¿qué hago?', "
            "'el ultrasonido dice que tengo un quiste de 2 cm, ¿es grave?'."
        ),
    },
    "condiciones_diagnosticadas": {
        "n": 7,
        "descripcion": (
            "Dudas de pacientes YA diagnosticados sobre cómo vivir con su "
            "condición. Ejemplo: 'tengo hipertensión, ¿puedo tomar café?', "
            "'soy diabético tipo 2, ¿puedo comer mango?'."
        ),
    },
    "prevencion_estilo_vida": {
        "n": 5,
        "descripcion": (
            "Preguntas de prevención, hábitos, alimentación o estilo de vida "
            "SIN síntoma ni diagnóstico de fondo. "
            "Ejemplo: '¿cada cuánto debería revisarme la presión si tengo 45 años?'."
        ),
    },
}

assert sum(c["n"] for c in DISTRIBUCION.values()) == 50, "La distribución no suma 50"

OUTPUT_PATH = BASE / "dataset_rag_medico_es.json"
CHECKPOINT_PATH = BASE / "dataset_rag_medico_es_checkpoint.json"
SAVE_EVERY = 10  # guardar el JSON cada N queries nuevas

PROMPT_TEMPLATE = """Eres un generador de queries realistas de pacientes hispanohablantes \
(LATAM, neutro con coloquialismos ocasionales) que buscan información médica en internet \
o en un chat de salud.

ÁREA MÉDICA OBJETIVO: {area}

TIPO DE QUERY A GENERAR:
{descripcion_tipo}

CANTIDAD: Genera EXACTAMENTE {n} queries de este tipo. Ni una más, ni una menos.

REGLAS DE VARIACIÓN (obligatorias):
- Mezcla registros: formal, informal, ansioso, casual, resignado.
- Mezcla demografías: adulto_joven (18-35), adulto_medio (36-55), \
adulto_mayor (56+), padre_madre (preguntando por su hijo/a), \
cuidador (preguntando por alguien a su cargo).
- Varía complejidad: simple, media, compleja.
- Varía longitud: algunas de una línea, otras con contexto largo.
- NO uses plantillas repetitivas: que cada query suene distinta y orgánica.
- Incluye coloquialismos ("se me hincha", "me arde", "tengo aire", \
"siento como…") cuando el registro sea informal/ansioso.

CAMPO "sistemas": lista de los sistemas corporales involucrados. \
Valores válidos: respiratorio, cardiovascular, digestivo, nervioso, \
musculoesqueletico, endocrino, urinario, reproductivo, tegumentario (piel), \
sensorial (ojos/oídos), inmunologico, psicologico, hematologico.
Pueden ser uno o varios.

FORMATO DE SALIDA OBLIGATORIO:
Devuelve UN ÚNICO array JSON válido. NADA antes, NADA después. \
Sin markdown, sin backticks, sin comentarios.

Cada objeto debe tener EXACTAMENTE estos campos y valores:
{{
  "query": "string con la consulta del paciente",
  "registro": "formal" | "informal" | "ansioso" | "casual" | "resignado",
  "demografia": "adulto_joven" | "adulto_medio" | "adulto_mayor" | "padre_madre" | "cuidador",
  "sistemas": ["..."],
  "complejidad": "simple" | "media" | "compleja"
}}

Empieza tu respuesta directamente con '[' y termínala con ']'."""


def construir_prompt(area: str, cat_info: dict) -> str:
    return PROMPT_TEMPLATE.format(
        area=area,
        descripcion_tipo=cat_info["descripcion"],
        n=cat_info["n"],
    )

def extraer_json(texto: str):
    """Intenta parsear el texto como array JSON, limpiando casos comunes."""
    t = texto.strip()
    # Quitar fences ```json ... ``` si los hubiera
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t)
        t = re.sub(r"\s*```$", "", t)
    # Recortar al primer '[' y último ']' por si hay basura alrededor
    inicio = t.find("[")
    fin = t.rfind("]")
    if inicio != -1 and fin != -1:
        t = t[inicio : fin + 1]
    return json.loads(t)


def generar_lote(area: str, cat_key: str, cat_info: dict, reintentos: int = 3):
    """Llama a Claude pidiendo `cat_info['n']` queries y devuelve la lista parseada."""
    prompt = construir_prompt(area, cat_info)
    for intento in range(1, reintentos + 1):
        try:
            resp = client.messages.create(
                model=MODELO,
                max_tokens=8000,
                messages=[{"role": "user", "content": prompt}],
            )
            texto = resp.content[0].text
            data = extraer_json(texto)
            if not isinstance(data, list):
                raise ValueError("La respuesta no es un array")
            # Enriquecer con metadata fija
            for item in data:
                item["area"] = area
                item["tipo"] = cat_key
            return data
        except json.JSONDecodeError as e:
            print(f"     ⚠️ JSON inválido (intento {intento}): {e}")
            time.sleep(2)
        except Exception as e:
            print(f"     ⚠️ Error API (intento {intento}): {e}")
            time.sleep(5)
    print(f"     ❌ Falló tras {reintentos} intentos: {area} / {cat_key}")
    return []

def guardar_dataset(resultados):
    """Persiste el dataset al archivo principal."""
    OUTPUT_PATH.write_text(
        json.dumps(resultados, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def guardar_checkpoint(hechos):
    """Guarda solo qué (area, tipo) ya están terminados para poder reanudar."""
    CHECKPOINT_PATH.write_text(
        json.dumps([list(x) for x in hechos], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def cargar_estado():
    """Lee el dataset y checkpoint existentes si los hay."""
    resultados = []
    hechos = set()
    if OUTPUT_PATH.exists():
        try:
            resultados = json.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            resultados = []
    if CHECKPOINT_PATH.exists():
        try:
            hechos = set(tuple(x) for x in json.loads(CHECKPOINT_PATH.read_text(encoding="utf-8")))
        except json.JSONDecodeError:
            hechos = set()
    return resultados, hechos


def ejecutar():
    resultados, hechos = cargar_estado()
    desde_ultimo_guardado = 0

    total_lotes = len(AREAS) * len(DISTRIBUCION)
    lote_idx = 0

    if resultados:
        print(f"📂 Reanudando: {len(resultados)} queries previas en {OUTPUT_PATH.name}")

    for i, area in enumerate(AREAS, 1):
        print(f"\n[{i}/{len(AREAS)}] {area}")
        for cat_key, cat_info in DISTRIBUCION.items():
            lote_idx += 1
            clave = (area, cat_key)
            if clave in hechos:
                print(f"  ↪︎ {cat_key} ya hecho, saltando")
                continue
            print(f"  → [{lote_idx}/{total_lotes}] {cat_key} (n={cat_info['n']})...")
            lote = generar_lote(area, cat_key, cat_info)

            # Agregar items uno por uno y guardar cada SAVE_EVERY
            for item in lote:
                resultados.append(item)
                desde_ultimo_guardado += 1
                if desde_ultimo_guardado >= SAVE_EVERY:
                    guardar_dataset(resultados)
                    desde_ultimo_guardado = 0
                    print(f"     💾 autosave: {len(resultados)} totales")

            hechos.add(clave)
            guardar_checkpoint(hechos)
            print(f"     ✓ {len(lote)} queries de este tipo")
            time.sleep(1)  # cortesía con el rate limit

    # Guardado final por si quedaron <10 sin persistir
    if desde_ultimo_guardado > 0:
        guardar_dataset(resultados)
    print(f"\n✅ Total final: {len(resultados)} queries → {OUTPUT_PATH}")
    return resultados


resultados = ejecutar()

def auditar(resultados):
    print(f"\n📊 Total: {len(resultados)}")
    print(f"   Esperado: {len(AREAS) * 50} = {len(AREAS)} áreas × 50\n")

    print("Por área:")
    for area, n in Counter(r["area"] for r in resultados).items():
        print(f"  {area}: {n}")

    print("\nPor tipo:")
    for tipo, n in Counter(r["tipo"] for r in resultados).items():
        print(f"  {tipo}: {n}")

    print("\nPor registro:")
    for k, n in Counter(r.get("registro", "?") for r in resultados).most_common():
        print(f"  {k}: {n}")

    print("\nPor demografía:")
    for k, n in Counter(r.get("demografia", "?") for r in resultados).most_common():
        print(f"  {k}: {n}")

    print("\nPor complejidad:")
    for k, n in Counter(r.get("complejidad", "?") for r in resultados).most_common():
        print(f"  {k}: {n}")

    print("\n--- 3 ejemplos al azar ---")
    import random
    for ej in random.sample(resultados, min(3, len(resultados))):
        print(json.dumps(ej, ensure_ascii=False, indent=2))
        print()


auditar(resultados)

