# -*- coding: utf-8 -*-
"""embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hT5jlVsZ3QD4kZxwn48UZlZLqLCNi0o7
"""

!pip install -q onnxruntime transformers numpy

import urllib.request

MODEL_URL = "https://huggingface.co/Qdrant/paraphrase-multilingual-MiniLM-L12-v2-onnx-Q/resolve/main/model_optimized.onnx"
print("Descargando model_optimized.onnx (~235 MB)...")
urllib.request.urlretrieve(MODEL_URL, "model.onnx")  # lo guardas localmente como model.onnx si quieres
print("Listo.")

import onnxruntime as ort
from transformers import AutoTokenizer
import numpy as np

# Tokenizer del repo original (mismo tokenizer.json que tendrás en Flutter)
tokenizer = AutoTokenizer.from_pretrained(
    "Qdrant/paraphrase-multilingual-MiniLM-L12-v2-onnx-Q"
)

# Sesión ONNX con el modelo cuantizado (mismo que en Flutter)
session = ort.InferenceSession("model.onnx", providers=["CPUExecutionProvider"])

# Inspecciona inputs/outputs para entender la firma del modelo
print("Inputs:", [(i.name, i.shape) for i in session.get_inputs()])
print("Outputs:", [(o.name, o.shape) for o in session.get_outputs()])

INPUT_NAMES = {i.name for i in session.get_inputs()}
NEEDS_TOKEN_TYPE = "token_type_ids" in INPUT_NAMES

def mean_pooling(token_embeddings: np.ndarray, attention_mask: np.ndarray) -> np.ndarray:
    """Promedia embeddings de tokens ponderados por la attention mask."""
    mask = np.expand_dims(attention_mask, -1).astype(np.float32)
    summed = np.sum(token_embeddings * mask, axis=1)
    counts = np.clip(mask.sum(axis=1), a_min=1e-9, a_max=None)
    return summed / counts


def l2_normalize(vec: np.ndarray) -> np.ndarray:
    norm = np.linalg.norm(vec, axis=-1, keepdims=True)
    return vec / np.clip(norm, a_min=1e-9, a_max=None)


# ============================================================
# 3. Funciones de embedding: single (para golden) y batch (para dataset)
# ============================================================
def embed(text: str) -> list:
    """Embebe una sola query. Útil para el golden test."""
    enc = tokenizer(
        text, padding=True, truncation=True, max_length=128, return_tensors="np"
    )
    inputs = {
        "input_ids": enc["input_ids"].astype(np.int64),
        "attention_mask": enc["attention_mask"].astype(np.int64),
    }
    if NEEDS_TOKEN_TYPE:
        inputs["token_type_ids"] = enc.get(
            "token_type_ids", np.zeros_like(enc["input_ids"])
        ).astype(np.int64)

    outputs = session.run(None, inputs)
    token_embeddings = outputs[0]  # (1, seq_len, 384)
    pooled = mean_pooling(token_embeddings, enc["attention_mask"])
    normalized = l2_normalize(pooled)
    return normalized[0].tolist()

def embed_batch(texts: list, batch_size: int = 32) -> list:
    """Embebe muchas queries en batch. Mucho más rápido que one-by-one."""
    all_vecs = []
    for i in tqdm(range(0, len(texts), batch_size), desc="Embedding"):
        chunk = texts[i:i+batch_size]
        enc = tokenizer(
            chunk, padding=True, truncation=True, max_length=128, return_tensors="np"
        )
        inputs = {
            "input_ids": enc["input_ids"].astype(np.int64),
            "attention_mask": enc["attention_mask"].astype(np.int64),
        }
        if NEEDS_TOKEN_TYPE:
            inputs["token_type_ids"] = enc.get(
                "token_type_ids", np.zeros_like(enc["input_ids"])
            ).astype(np.int64)

        outputs = session.run(None, inputs)
        pooled = mean_pooling(outputs[0], enc["attention_mask"])
        normalized = l2_normalize(pooled)
        all_vecs.extend(normalized.tolist())
    return all_vecs

test = embed("hola mundo")
print(f"Dimensiones: {len(test)}")           # esperado: 384
print(f"Primeros 5 valores: {test[:5]}")
print(f"Norma: {np.linalg.norm(test):.4f}")  # esperado: ~1.0

import json
golden_test = {"text": "hola mundo", "vector": test}
with open("golden_test.json", "w") as f:
    json.dump(golden_test, f)
print("Golden test guardado.")

import json

# 1. Cargar el dataset original
with open("dataset_rag_medico_es_enriched.json", "r", encoding="utf-8") as f:
    enriquecimientos = json.load(f)

# 2. Inyectar id basado en la posición
for idx, e in enumerate(enriquecimientos):
    e["id"] = idx

# 3. Guardar como archivo nuevo (no sobrescribe el original)
output_path = "dataset_rag_medico_es_enriched_with_ids.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(enriquecimientos, f, ensure_ascii=False, indent=2)

print(f"Guardado: {output_path}")
print(f"Total registros: {len(enriquecimientos)}")
print(f"Primer registro: id={enriquecimientos[0]['id']}, query={enriquecimientos[0].get('query', '')[:60]}...")
print(f"Último registro: id={enriquecimientos[-1]['id']}")

# 4. (Opcional) descargar el archivo a tu máquina
from google.colab import files
files.download(output_path)

with open("data_ids.json", "r", encoding="utf-8") as f:
    enriquecimientos = json.load(f)

print(f"Total enriquecimientos: {len(enriquecimientos)}")

# 5a. Aplanar: una lista de textos + metadata paralela
flat_texts = []
flat_meta = []

for e in enriquecimientos:
    queries = e.get("queries") or [e["query"]]
    for variant_idx, q in enumerate(queries):
        flat_texts.append(q)
        flat_meta.append({"id": e["id"], "variant": variant_idx})

print(f"Total queries a embeber: {len(flat_texts)}")

# Vectores precomputados
with open("vectors.json", "w", encoding="utf-8") as f:
    json.dump(vectors, f)

# Enriquecimientos canónicos (sin las queries, porque ya están embebidas)
# Mantenemos solo lo que se va a renderizar en UI
canonical = []
for e in enriquecimientos:
    canonical.append({
        "id": e["id"],
        "area": e.get("area"),
        "tipo": e.get("tipo"),
        "complejidad": e.get("complejidad"),
        "enriquecimiento": e["enriquecimiento"],
    })

with open("enriquecimientos.json", "w", encoding="utf-8") as f:
    json.dump(canonical, f, ensure_ascii=False)

# Tamaños
import os
for name in ["vectors.json", "enriquecimientos.json", "golden_test.json"]:
    size_kb = os.path.getsize(name) / 1024
    print(f"{name}: {size_kb:.1f} KB")

from google.colab import files
files.download("vectors.json")
files.download("enriquecimientos.json")
files.download("golden_test.json")